### ISSUE TITLE
Global app / scope not available

### ISSUE THREAD

**Issue by philippeluickx** [RaynorUE/snich#121]
**Describe the bug**
Trying to do a pull of global / global. List of applications does not show it though.

**To Reproduce**
Connect and pull.
Note: we have the Fiscal Calendar app active, which is also of a global scope. I suspect that this extension only picks the first app with global scope. There can be multiple however.

**Expected behavior**
All apps with global scope should show up, including global / global

**Desktop (please complete the following information):**
 - OS: windows 10

**Additional context**
I can see any other custom app / scope fine and sync.

**Comment by RaynorUE** [comment]
Phillippe,

Can you ellaborate a bit more on what you're trying to do? Are you looking to sync every file from global scope..? Never thought about it before, but suppose it would work okay... but could be pretty confusing with all the files that come down.

Something we have been considering is the option to sync global apps via their "Package" (If you look at sys_metadata and the packge field) you'll see things like "Incident, Change, etc" In which ServiceNow seems to be doing a good job getting all the associated items in there. 

Would that work? or are you looking for something entirely different?

**Comment by philippeluickx** [comment]
@RaynorUE Sure!
We are doing quite some development in the global scope (for reasons) and I'd love to get all this work in VSCode.
I'm mostly interested in the custom scripts, but getting every file that is accessible in Core would be interesting as well... If you can do it per "package" I think that makes a lot of sense. Not sure if there's anything in global that would not have a "package" though.

**Comment by RaynorUE** [comment]
I follow ya know Phillippe,

In the near term, can you try using the "SNICH: Sync record" command? It might be a bit tedious since you'll have to do one file at a time... but it should let you access any file regardless of scope.. 

hoping to get the "Sync Global Apps by Package" command in there this week or next week..

**Comment by philippeluickx** [comment]
Thanks, that sounds great! And good job on the plugin!

**Comment by philippeluickx** [comment]
@RaynorUE Did you manage to have a look at this?
Have a great day!

**Comment by RaynorUE** [comment]
Given the ambiguity of Global scope, we'll rely on the sync on at a time for the moment. I did look into sync by "package" but it will never retrieve anything created new/custom (new BR's, script includes, etc) due to not being able to set the package field on new items, basically forcing you to sync manually all the time anyway.

For the time being I probably won't be doing any dev work to get this any further since "Scoped apps are the future" (even all of SN's new apps are scoped). Which would load in here.. you just need to go into vscode settings and checkbox the "Show SN Apps" flag to have them show in the app picker.
