### ISSUE TITLE
Where are the logs?

### ISSUE THREAD

**Issue by NainRouge** [RaynorUE/snich#90]
**Describe the bug**
Test Connection failed.  Unknown Error.  View logs for details

**To Reproduce**
Test a connection that worked yesterday

**Expected behavior**
Let me know where to view logs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10.

**Comment by RaynorUE** [comment]
Hey thanks for posting this! you're the first "Stranger" (I know all the other people so far) to the project to post the first issue! Feel like i should have an award for that or something... hahaha. 

**Regarding logging**
To set the "Logging level" you can go into the VSCode Settings (Cogwheel in bottom left) and search for "SNICH" (or use the left nav in settings to expand extensions and select SNICH). 
You'll see a "Logging Level" there, it most likely defaults to "errors"... but recommend updating that to "Debug". 

Then you'll be able to view the logs by clicking on "Help" in VSCode and choosing "Toggle developer tools". 

**Regarding your Test connection failure**
The most common causes are:

1.  Ensure you're UserName has a "local password" on your instance. (Go into your user record and set a password using the password field). The SN REST API does not support SSO. 
2. Make sure you type in JUST the instance name. I.e.: _MyDev_ instead of _MyDev.service-now.com_. Alternatively you can type in the full URL: https://mydev.service-now.com

**Comment by NainRouge** [comment]
Hahaha, it's a great extension.  Surprised I'm the first one outside of your circle to be a known user.

Thanks for the tip on where to find the logs though.   To be more detailed about what I'm running into is that this worked about a week ago and just stopped.  My team mate uses it as well without issue so I shouldn't be running into any blocking.  Unfortunately though, the logs only say this:

> Data to be logged may have contained a password. Not logging.

Is there a way to have it spit them out anyhow?

**Comment by NainRouge** [comment]
Is there a timeout on oauth connection tests?  I went to setup the instance from scratch as oauth instead of basic and it's been testing for over 10 minutes.

**Comment by integratenate** [comment]
Hey there!

Sooooooooo. The oAuth stuff was "Put in, tested once, and I never looked back". Mostly cuase I did not expect a whole lot of people wanting to use it. 

It definitely needs some more polish (and i'll use this issue to make those updates when the time comes). 

In the mean time, it looks like some of the "Prompts" when settingup oAuth I forgot to set a flag for the input boxes, where if you "alt-tab" or "click out of the input box" it skips ahead and the code and starts trying to test the connection... What's funny, is it's just showing the message and  not actually testing anything for 10 minutes... 

I'll end up getting these fixed. However, in the near term i've thrown together a quick few screenshots and a quick write-up of the steps that should need performed... You can access here: https://docs.google.com/presentation/d/1mlfl1rG5pJkuR8sl9AEKutQI8FGv7MayQMhIYyULmWk/edit?usp=sharing

**Comment by RaynorUE** [comment]
Just wanted to update before closing this issue, that the oAuth path should flow / work nicely now. I still plan on recording a video on it at some point.
